### PR TITLE
Add implementation for ABCL

### PR DESCRIPTION
**Pull request by wahjava**
This pull request adds implementation for ABCL, which works fine. `timeout` stuff is not implemented atm, though.

Thanks!

### CODE REVIEW

**Comment by gwkkwg** [comment]
Thanks. Sorry it took so long for me to pull it in.

**Comment by wahjava** [comment]
Howdy,

No worries about the delay. I'm wondering where did the commits go. Looks like you just closed the PR, instead of merging/pulling the changes.

Thanks!

**Comment by gwkkwg** [comment]
Whoops. My apologies (again!). I'll rectify this over the weekend.

**Comment by gwkkwg** [comment]
Hmmm. My github foo is sadly lacking. I'm not seeing an obvious way to re-open the pull request. Can you submit the request again?

**Comment by gwkkwg** [comment]
Ah, re-opening the request seems to have done the trick. I think we're good to go. Let me know if there's anything still amiss.

**Comment by wahjava** [comment]
Nope, all good, sir.

Thanks, and have a great week to you! :)

**Pull request merged**
